config/routes.rb
Rails.application.routes.draw do
  resources :days
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/day.rb
class Day < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    has_many :days
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/days_controller.rb
class DaysController < ApplicationController
    
    # MUST INCLUDE THIS
    layout false 

    # Or this error will show:
    # Webpacker can't find application in /Users/leighadelarosa/workspace/rails-practice/day-by-day/public/packs/manifest.json. Possible causes:
    # 1. You want to set webpacker.yml value of compile to true for your environment
    # unless you are using the `webpack -w` or the webpack-dev-server.
    # 2. webpack has not yet re-run to reflect updates.
    # 3. You have misconfigured Webpacker's config/webpacker.yml file.
    # 4. Your webpack configuration is not creating a manifest.
    # Your manifest contains:
    # {
    # }

    def index
        @days = Day.all 
    end

    def show 
        set_day
    end

    def new 

    end

    def create 

    end

    private

    def set_day
        @day = Day.find_by_id(params[:id])
    end

    def day_params
        params.require(:day).permit(:date, :title, :content, :favorite, :user_id)
    end

    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/days_helper.rb
module DaysHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/days/index.html.erb
<h2>List of Days</h2>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @days.each do |day| %>
      <tr>
        <td><%= day.title %></td>
        <td><%= day.content %></td>
        <td><%= link_to "Show", day %></td>
        <td><%= link_to "Edit", edit_day_path(day) %></td>
        <td><%= link_to "Destroy", day, method: :delete, data: { confirm: "Are you sure?" } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to "New Day", new_day_path %>

app/views/days/show.html.erb
<h2>On This Day:</h2>

<table>
  <thead>
    <tr>
      <th>Date</th>
      <th>Title</th>
      <th>Content</th>
      <th>Favorite?</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
      <tr>
        <td><%= @day.date %></td>
        <td><%= @day.title %></td>
        <td><%= @day.content %></td>
        <td><%= @day.favorite %></td>
        <td><%= link_to "Show", @day %></td>
        <td><%= link_to "Edit", edit_day_path(@day) %></td>
        <td><%= link_to "Destroy", @day, method: :delete, data: { confirm: "Are you sure?" } %></td>
      </tr>
  </tbody>
</table>

<br>

<%= link_to "New Day", new_day_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DayByDay</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>